services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - rede_ava

  projeto_ava:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: projeto_ava
    environment:
      - POSTGRES_DB=postgres
      - PORT=5432
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - rede_ava

networks:
  rede_ava:
    driver: bridge
