services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - minha-rede

  projeto_ava:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: projeto_ava
    environment:
      - POSTGRES_DB=postgres
      - PORT=5432
    depends_on:
      - postgres
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
